import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { ReactNode, startTransition } from "react";
import { dark } from "@clerk/themes";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { unstable_ViewTransition as ViewTransition } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: Readonly<{ children: ReactNode }>) => {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,

        layout: {
          shimmer: true,
          animations: true,
        },

        variables: {
          colorBackground: "#02061899",
        },
      }}
    >
      <ViewTransition>
        <html lang="en" suppressHydrationWarning={true}>
          <body className="flex justify-center items-center bg-[#020618ee]">
            <main className="flex justify-between w-full">
              <section className="flex mx-4 my-4">
                <Link href="/">
                  <Button size={"lg"}>Home</Button>
                </Link>
              </section>

              <section className="flex flex-col items-center justify-center w-1/2 max-[950px]:w-full max-[950px]:h-screen">{children}</section>

              <section className="sm:block">
                <img src="/images/auth-illustration.png" alt="auth illustration" className="h-screen w-[50vw] object-cover max-[950px]:hidden" />
              </section>
            </main>
          </body>
        </html>
      </ViewTransition>
    </ClerkProvider>
  );
};

export default RootLayout;
